### ISSUE TITLE
Serving tangram models in the browser with WASM

### ISSUE THREAD

**Issue by marionebl** [tangramxyz/tangram#3]
I'm interested in deploying tangram models client-side via WASM. Is this something you'd be interested in to support officially?

 In any case I'd be keen to experiment in that direction, any pointers as to how  to get started on this?

**Comment by nitsky** [comment]
We definitely want to support deploying tangram models client-side via WASM. I am working on this now, I'll get back to you soon.

**Comment by nitsky** [comment]
Hi Mario, we published a new release which has support for client-side WASM. If you are working on a JS/TS project with webpack, add the [@tangramxyz/tangram](https://npmjs.com/@tangramxyz/tangram) npm package to your project and add the following to your webpack configuration:

1. Enable wasm support:

```javascript
experiments: {
  asyncWebAssembly: true,
  topLevelAwait: true,
},
```

2. Use the file-loader plugin for `.tangram` files:

```javascript
module: {
  rules: [
    {
      test: /\.tangram$/,
      type: "file-loader",
    },
  ],
},
```

Then, you can make a prediction like so:

```javascript
import * as tangram from "@tangramxyz/tangram"
import heartDiseaseModelUrl from "../../heart_disease.tangram"

// Download the model.
let modelResponse = await fetch(heartDiseaseModelUrl)
let modelData = await modelResponse.arrayBuffer()
// Load the model.
let model = new tangram.Model(modelData)

// Create an example input matching the schema of the CSV file the model was trained on. Here the data is just hard-coded, but in your application you will probably get this from a database or user input.
let input = {
  age: 63,
  // ...
}

// Make the prediction!
let output = model.predict(input)

// Print the output.
console.log("Output:", output)
```

Does this setup work for you?

**Comment by marionebl** [comment]
Awesome, works like a charm! A follow up consideration would be best practices / tools to decrease raw file size of models. I'll experiment a bit with that. Thank you so much :)

**Comment by nitsky** [comment]
@marionebl Currently `.tangram` files include not just the information necessary to make predictions but also everything that shows up in the web app. We plan to add a CLI subcommand `tangram optimize` that will strip this extra information and minimize the size of the model as much as possible without lowering accuracy too much. You can also use a config file to limit training to consider only linear models or tree models with a small number of trees to keep the model size down.
