### ISSUE TITLE
Model documentation

### ISSUE THREAD

**Issue by rustrust** [tangramxyz/tangram#6]
I'm reading through the documentation on tangram.xyz but don't see any indication of what model or combination of models tangram is selecting for the data. Can you please provide some documentation on this? Thanks!

**Comment by nitsky** [comment]
@rustrust I agree, we need to do a better job explaining this in the docs.

Tangram determines the task (either regression, binary classification, or multiclass classification) based on the type of the target column. If the target column is a `Number` column, the task will be regression. If the target column is an `Enum` column with two variants, the task will be binary classification. If the target column is an `Enum` column with more than two variants, the task will be multiclass classification.

Then, tangram trains a grid of linear and gradient boosted decision tree models for the selected task. The definition of the default grid for each task is in this file: https://github.com/tangramxyz/tangram/blob/main/crates/core/grid.rs.

Alternatively, you can specify your own grid in a JSON configuration file passed to `tangram train` with the `--config` flag. You can see an example in the docs at https://www.tangram.xyz/docs/guides/train_with_custom_configuration. The best documentation for the schema of the configuration file is the `serde` type definitions in the source: https://github.com/tangramxyz/tangram/blob/main/crates/core/config.rs.

Let me know if this answers your question or if you want more information.

I will leave this issue open until we update the docs with better information on this.

**Comment by nitsky** [comment]
@isabella added an "internals" section to the docs which covers what tasks tangram supports, how it performs feature engineering, and what model types are trained.

**Comment by isabella** [comment]
@rustrust I've added an internals section to the docs that explains the hyperparameter grid, the model and task types, and the feature engineering. Let us know if there is anything else that we can clarify in the docs!
