### ISSUE TITLE
Building from source and running 

### ISSUE THREAD

**Issue by rustrust** [tangramxyz/tangram#7]
Can you please provide very straightforward instructions on building from source? The scripts aren't straightforward to use. Additionally, it would be more idiomatic for a rust repo like this to include at least one example which is easy to run, like so:

```
cargo run --example heart_disease
```

I would also suggest including the heart_disease.csv test file in your github repo so folks compiling from source can have a command like the above (or a script could do this...)

**Comment by nitsky** [comment]
@rustrust check out the "Contributing" section of the README. Is that sufficient to get started?

This repo is a cargo workspace and the `tangram_cli` is the default `bin`, so you can just run `cargo run` to run a debug build of the CLI, or `cargo build --release` to produce a release build.

Each language library also contains a number of examples, as described in a `README.md` file in each subdirectory under `langauges`. For Rust, navigate to `languages/rust` and run `cargo run --example basic` to run the basic example which makes predictions with a pretrained heart disease model.

You can download the heart disease example dataset from the docs at https://www.tangram.xyz/docs/getting_started/train or from our "datasets" public S3 bucket at http://datasets.tangram.xyz/heart_disease.csv.
